Practicas\Bundle\Practica1Bundle\Entity\Usuario:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    nombre:
      type: string
      length: 255
    apellidos:
      type: string
      length: 255
    telefono:
      type: string
      length: 9
    direccion:
      type: string
      length: 255
  manyToOne:
    curso:
      targetEntity: Curso
      inversedBy: cursoid
  lifecycleCallbacks: {  }
